version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    #volumes:
    #  - logs:/app/logs
    environment:
      - FLASK_ENV=development
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge